// Code generated by "stringer -type=ObjectType"; DO NOT EDIT.

package runtime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PoisonType-0]
	_ = x[NilType-1]
	_ = x[ThunkType-2]
	_ = x[FunType-3]
	_ = x[BoolType-4]
	_ = x[IntType-5]
	_ = x[RealType-6]
	_ = x[ComplexType-7]
	_ = x[ListType-8]
	_ = x[DataType-9]
}

const _ObjectType_name = "PoisonTypeNilTypeThunkTypeFunTypeBoolTypeIntTypeRealTypeComplexTypeListTypeDataType"

var _ObjectType_index = [...]uint8{0, 10, 17, 26, 33, 41, 48, 56, 67, 75, 83}

func (i ObjectType) String() string {
	if i < 0 || i >= ObjectType(len(_ObjectType_index)-1) {
		return "ObjectType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
