// Code generated by "stringer -type=TokenKind"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[specialBeg-0]
	_ = x[Comment-1]
	_ = x[Skip-2]
	_ = x[Mismatch-3]
	_ = x[Eof-4]
	_ = x[specialEnd-5]
	_ = x[literalBeg-6]
	_ = x[Ident-7]
	_ = x[Integer-8]
	_ = x[Real-9]
	_ = x[Complex-10]
	_ = x[String-11]
	_ = x[Boolean-12]
	_ = x[literalEnd-13]
	_ = x[operatorBeg-14]
	_ = x[strictlyUnaryOperatorBeg-15]
	_ = x[Not-16]
	_ = x[BNot-17]
	_ = x[strictlyUnaryOperatorEnd-18]
	_ = x[unaryBinaryOperatorBeg-19]
	_ = x[Plus-20]
	_ = x[Minus-21]
	_ = x[unaryBinaryOperatorEnd-22]
	_ = x[Percent-23]
	_ = x[Star-24]
	_ = x[DoubleStar-25]
	_ = x[Slash-26]
	_ = x[DoubleSlash-27]
	_ = x[SlashPercent-28]
	_ = x[Colon-29]
	_ = x[DoubleColon-30]
	_ = x[At-31]
	_ = x[On-32]
	_ = x[Less-33]
	_ = x[LessEqual-34]
	_ = x[Greater-35]
	_ = x[GreaterEqual-36]
	_ = x[Equal-37]
	_ = x[DoubleEqual-38]
	_ = x[ExclamationEqual-39]
	_ = x[DoubleExclamation-40]
	_ = x[DoublePlus-41]
	_ = x[And-42]
	_ = x[BAnd-43]
	_ = x[Or-44]
	_ = x[BOr-45]
	_ = x[Xor-46]
	_ = x[BXor-47]
	_ = x[DashGreater-48]
	_ = x[VerticalBarGreater-49]
	_ = x[operatorEnd-50]
	_ = x[keywordBeg-51]
	_ = x[Module-52]
	_ = x[Using-53]
	_ = x[As-54]
	_ = x[Case-55]
	_ = x[Of-56]
	_ = x[If-57]
	_ = x[Then-58]
	_ = x[Elif-59]
	_ = x[Else-60]
	_ = x[Let-61]
	_ = x[Rec-62]
	_ = x[In-63]
	_ = x[Def-64]
	_ = x[Fn-65]
	_ = x[Otherwise-66]
	_ = x[keywordEnd-67]
	_ = x[separatorBeg-68]
	_ = x[Comma-69]
	_ = x[Period-70]
	_ = x[LeftParenthesis-71]
	_ = x[RightParenthesis-72]
	_ = x[LeftBracket-73]
	_ = x[LeftBracelet-74]
	_ = x[RightBracelet-75]
	_ = x[RightBracket-76]
	_ = x[Quote-77]
	_ = x[Ellipsis-78]
	_ = x[Semicolon-79]
	_ = x[QuestionMark-80]
	_ = x[Tab-81]
	_ = x[Space-82]
	_ = x[Newline-83]
	_ = x[Eos-84]
	_ = x[separatorEnd-85]
}

const _TokenKind_name = "specialBegCommentSkipMismatchEofspecialEndliteralBegIdentIntegerRealComplexStringBooleanliteralEndoperatorBegstrictlyUnaryOperatorBegNotBNotstrictlyUnaryOperatorEndunaryBinaryOperatorBegPlusMinusunaryBinaryOperatorEndPercentStarDoubleStarSlashDoubleSlashSlashPercentColonDoubleColonAtOnLessLessEqualGreaterGreaterEqualEqualDoubleEqualExclamationEqualDoubleExclamationDoublePlusAndBAndOrBOrXorBXorDashGreaterVerticalBarGreateroperatorEndkeywordBegModuleUsingAsCaseOfIfThenElifElseLetRecInDefFnOtherwisekeywordEndseparatorBegCommaPeriodLeftParenthesisRightParenthesisLeftBracketLeftBraceletRightBraceletRightBracketQuoteEllipsisSemicolonQuestionMarkTabSpaceNewlineEosseparatorEnd"

var _TokenKind_index = [...]uint16{0, 10, 17, 21, 29, 32, 42, 52, 57, 64, 68, 75, 81, 88, 98, 109, 133, 136, 140, 164, 186, 190, 195, 217, 224, 228, 238, 243, 254, 266, 271, 282, 284, 286, 290, 299, 306, 318, 323, 334, 350, 367, 377, 380, 384, 386, 389, 392, 396, 407, 425, 436, 446, 452, 457, 459, 463, 465, 467, 471, 475, 479, 482, 485, 487, 490, 492, 501, 511, 523, 528, 534, 549, 565, 576, 588, 601, 613, 618, 626, 635, 647, 650, 655, 662, 665, 677}

func (i TokenKind) String() string {
	if i < 0 || i >= TokenKind(len(_TokenKind_index)-1) {
		return "TokenKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenKind_name[_TokenKind_index[i]:_TokenKind_index[i+1]]
}
